### ISSUE TITLE
OrderedDict

### ISSUE THREAD

**Issue by dandxy89** [anujgupta82/DeepNets#1]
Hi,

You may want to check that the ordering of the w2index and int2vector ordering is consistent between the two.

Might not be an issue with this example, but I have noticed in my current work that it may be an issue. It really depends on how you are building your dictionaries.

**Comment by dandxy89** [comment]
Please close this issue

**Comment by anujgupta82** [comment]
@dandxy89 : sorry for coming back on this so late but can you be more specific what mistake you are pointing to ?
